name: Plugin CI
# 使用 Github Actions 和 gh-pages 搭建 web 应用
on:
  push:
    branches: [ main ]  # 这里是你当前主分支的名字,我这里是main,你的可能是master
    paths-ignore:
      - README.md     # 表示该文件更新不会触发Github Actions部署,自行配置即可
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 构建插件信息
        run: |
          cd pluginReleaseParse
          npm install
          npm run build

      - name: 构建官网前端
        run: |
          cd web_site_project
          npm install
          npm run docs:build
          cp -r ./docs/.vitepress/dist/* ../pages/

      - name: Deploy Plugin Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MEDIABOXTOKEN }}  # 仓库token秘钥!!!
          publish_dir: ./pages  # 打包后文件的输出目录(根据你自己的项目情况而定)
          commit_message: 自动部署 # 部署时的 git 提交信息，自由填写